repositories:
  - name: jetstack          # Name used to reference this repository
    url: https://charts.jetstack.io # Official Cert Manager Helm chart repository
  - name: adfinis
    url: https://charts.adfinis.com
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

# Define the releases (deployments)
releases:
  # Release definition for Cert Manager
  - name: cert-manager             # Name of the Helm release (visible in 'helm list')
    namespace: cert-manager        # Target namespace for installation
    chart: jetstack/cert-manager   # Chart reference: <repository_name>/<chart_name>
    version: v1.17.1             # <--- IMPORTANT: Pin to a specific chart version! Check for the latest stable version.
    createNamespace: true          # Ask Helmfile/Helm to create the namespace if it doesn't exist (still good practice to create it manually first)
    values:
      - installCRDs: true
  - name: cert-manager-issuers             # Name of the Helm release (visible in 'helm list')
    namespace: cert-manager        # Target namespace for installation
    chart: adfinis/cert-manager-issuers   # Chart reference: <repository_name>/<chart_name>
    version: 0.3.0             # <--- IMPORTANT: Pin to a specific chart version! Check for the latest stable version.
    createNamespace: true          # Ask Helmfile/Helm to create the namespace if it doesn't exist (still good practice to create it manually first)
    needs: 
      - cert-manager
    values:
      - config/cert-manager-issuer/values.yaml      
  - name: prom-norbac-ubuntu
    namespace: prometheus
    chart: prometheus-community/prometheus
    set:
    - name: rbac.create
      value: false
  - name: nginx
    namespace: nginx
    chart: ingress-nginx/ingress-nginx
